# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target


#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

all:
	@echo "Compiling..."
.PHONY : all

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tui"
	@echo "... src/app/main.o"
	@echo "... src/app/main.i"
	@echo "... src/app/main.s"
	@echo "... src/lib/fontconfig.o"
	@echo "... src/lib/fontconfig.i"
	@echo "... src/lib/fontconfig.s"
.PHONY : help
